name: rocket_chat_dart
description: Similar to Rocket.Chat.Go.SDK and implement APIs according to the Rocket Chat document.
version: 0.0.39+1
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/rocket.chat.dart
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  ddp: ^0.0.13
  crypto: ^2.1.4
  http: ^
  json_annotation: ^3.0.1

dev_dependencies:
  test: ^1.14.3
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
